Add label so type includes `repeated`
protobuffet/docusaurus-protobuffet pull request #7
Opened 2022-08-16 23:02 UTC by Breefield

2022-08-30 17:26 UTC, AnthonyBobsin commented on packages/docusaurus-protobuffet-plugin/src/theme/ProtoFile.tsx
> +      { if(field.label != "") {
there are some code formatting issues here that will break things. can we conditionally inject this in a different way?

2022-08-30 17:26 UTC, AnthonyBobsin requested changes
I don't think this will render based on code formatting issues. Please test, let me know if you need assistance.

2022-11-15 21:24 UTC, Breefield commented
Hey @AnthonyBobsin I think I've got this written a little more cleanly/without syntax errors (I hope, I don't write TSX).

2022-12-13 17:50 UTC, Breefield commented
Hey @AnthonyBobsin, would you like any additional changes?

2022-12-13 18:38 UTC, AnthonyBobsin commented
@Breefield thanks for addressing the changes! I tested it out and found a minor issue with the rendering.

<img width="782" alt="image" src="https://user-images.githubusercontent.com/9815543/207416096-1966a612-34bb-464e-a284-c01974cf76c3.png">

For types with links, the label value is included in the link. I think we should change this behaviour to exclude the label value from the link.

Here is a code snippet applying the suggested behaviour. Please apply these changes and I'll merge after that fix.


```tsx
const FieldTypeCell = ({ field }: { field: MessageField}) => {
  const typeCell = field.typeLink === undefined
    ? <code>{field.longType}</code>
    : <Link to={field.typeLink}><code>{field.longType}</code></Link>;

  return (
    <span>
      {field.label !== "" && <i>{field.label}&nbsp;</i>}
      {typeCell}
    </span>
  )
}
```

<img width="781" alt="image" src="https://user-images.githubusercontent.com/9815543/207415853-be4e4850-2015-435c-ba34-7ba4ca0b02b0.png">

2023-02-21 17:05 UTC, Breefield commented
@AnthonyBobsin modified!

2023-03-03 14:47 UTC, merged

2023-03-03 15:09 UTC, AnthonyBobsin commented
@Breefield Thanks for adding this feature! I've released it under version 0.3.3.